import { MigrationInterface, QueryRunner } from 'typeorm';

export class AutoGenerated1768632223792 implements MigrationInterface {
  name = 'AutoGenerated1768632223792';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`quote\` (\`id\` int NOT NULL AUTO_INCREMENT, \`text\` varchar(255) NOT NULL, \`userId\` int NOT NULL, \`createdAt\` datetime NOT NULL, INDEX \`IDX_bcbf020650ca118abc4cc1ceea\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`quote_posting\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quoteId\` int NOT NULL, \`postCount\` int NOT NULL DEFAULT '0', \`lastPostedAt\` datetime NULL, INDEX \`IDX_7dc0d0aa5f52a7e5c455902668\` (\`quoteId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NULL, \`messengerId\` varchar(100) NOT NULL, \`isActive\` tinyint NOT NULL, \`createdAt\` datetime NOT NULL, \`lastPostedAt\` datetime NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `ALTER TABLE \`quote_posting\` ADD CONSTRAINT \`FK_7dc0d0aa5f52a7e5c455902668b\` FOREIGN KEY (\`quoteId\`) REFERENCES \`quote\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`quote_posting\` DROP FOREIGN KEY \`FK_7dc0d0aa5f52a7e5c455902668b\``,
    );
    await queryRunner.query(`DROP TABLE \`user\``);
    await queryRunner.query(
      `DROP INDEX \`IDX_7dc0d0aa5f52a7e5c455902668\` ON \`quote_posting\``,
    );
    await queryRunner.query(`DROP TABLE \`quote_posting\``);
    await queryRunner.query(
      `DROP INDEX \`IDX_bcbf020650ca118abc4cc1ceea\` ON \`quote\``,
    );
    await queryRunner.query(`DROP TABLE \`quote\``);
  }
}
